//Plantation related
export const SUBMIT_FFB_TOKEN = "@@SUBMIT_FFB_TOKEN";
export const REQUEST_PLANTATION_ACCESS = "@@REQUEST_PLANTATION_ACCESS";
export const SET_TOKENS_SUBMITTED = "@@GET_TOKENS_SUBMITTED";
export const SET_CURRENT_PLANTATION = "@@SET_CURRENT_PLANTATION";

//Consortium Related
export const SET_AVAILABLE_CONSORTIUMS = "@@SET_AVAILABLE_CONSORTIUMS";
export const SET_AVAILABLE_PLANTATIONS = "@@SET_AVAILABLE_PLANTATIONS";
export const SET_CURRENT_CONSORTIUM_ADDRESS = "@@SET_CURRENT_CONSORTIUM_ADDRESS";
export const SET_CURRENT_CONSORTIUMDEPLOYER_ADDRESS = "@@SET_CURRENT_CONSORTIUMDEPLOYER_ADDRESS";
export const SET_PLANTATION_INFORMATION = "@@SET_PLANTATION_INFORMATION";


//RSPO Related
export const SET_RSPO_ADMIN = "@@SET_RSPO_ADMIN"


//Mill Related

//Authentication Related
export const SET_AUTHENTICATED_TYPE = "@@SET_AUTHENTICATED_TYPE";
export const AUTHENTICATE_USER = "@@AUTHENTICATE_USER";
export const SET_ACCOUNTS_LIST = "@@SET_ACCOUNTS_LIST";
export const SET_USER_ADDRESS = "@@SET_USER_ADDRESS";
